### ISSUE TITLE
Examples fail with multiple headings on one MOC page.

### ISSUE THREAD

**Issue by ShayHill** [seqis/ObsidianMOC#1]
Great tutorial. Thank you.

I followed this tutorial to set up a Maps of Content system. Pasting the examples, I was able to get working references.

```
Philosophy MOC (this is the note title)

## Stoicism
```dataview
list from ""
where contains(file.outlinks, [[Philosophy MOC#Stoicism]])
sort file.mtime desc
```

However, that only worked when I had one heading per MOC page. With multiple headings, I had to close the three back-tics on ` ```dataview` lines to get everything working.

````
Philosophy MOC (this is the note title)

## Stoicism
```dataview
list from ""
where contains(file.outlinks, [[Philosophy MOC#Stoicism]])
sort file.mtime desc
```

## Marcus Aurelius
```dataview
list from ""
where contains(file.outlinks, [[Philosophy MOC#Marcus Aurelius]])
sort file.mtime desc
```
````

**Comment by seqis** [comment]
Yes you're right .... when I formatted my markdown code windows in my post, the last 3 backticks ``` at the bottom of every query didn't show, but they should be there to close the code window. You're correct.

I'll edit the document to fix all that. I'm glad it was helpful to you though!! I have a little under 1000 notes in my vault and it's how I manage the whole thing.
